name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update
        run: |
          sudo apt-get update

      - name: Setup Conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          conda env create -f ccg_backend/environment.yml

      - name: Run Flake8
        run: |
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate myenv
          pip install flake8
          flake8 flake8 --config=ccg_backend/.flake8 ccg_backend/

      - name: Run backend tests
        run: |
          cd ccg_backend
          conda init bash
          source ~/miniconda/etc/profile.d/conda.sh
          conda activate myenv
          pytest

  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4

      - name: Install frontend dependencies
        run: |
          cd ccg_frontend/ccg_mobile
          npm install -g expo-cli
          npm install --legacy-peer-deps
          npm run test

      - name: Run ESLint
        run: |
          cd ccg_frontend/ccg_mobile
          npm install --save-dev eslint@8
          npm install eslint-plugin-react@latest --save-dev
          npm install @typescript-eslint/eslint-plugin@latest --save-dev
          npx eslint .
