name: CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update
        run: |
          sudo apt-get update

      - name: Set up Conda environment
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          cd ccg_backend
          conda env create -f environment.yml
          conda init bash
          conda activate myenv
          conda list

      - name: Run backend tests
        run: |
          pytest 

  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4

      - name: Install frontend dependencies
        run: |
          cd ccg_frontend/ccg_mobile
          npm install -g expo-cli
          npm install --legacy-peer-deps
          npm run test
